spring.application.name=question-service
spring.data.mongodb.uri=mongodb+srv://nirav:nirav%402896@dsa-platform.kkbl1ev.mongodb.net/Dsa-platform?appName=Dsa-platform
spring.data.mongodb.database=question-service
spring.jackson.mapper.accept-case-insensitive-enums=true
server.port=8081
testcase.storage.path=backend/testcases

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
